# Generated by Django 4.2.5 on 2024-07-20 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='grade',
            fields=[
                ('id_grade', models.AutoField(primary_key=True, serialize=False)),
                ('nama_grade', models.CharField(max_length=100)),
                ('deskripsi_grade', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='jenisbiaya',
            fields=[
                ('idjenisbiaya', models.AutoField(primary_key=True, serialize=False)),
                ('jenis_biaya', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='mitra',
            fields=[
                ('id_mitra', models.AutoField(primary_key=True, serialize=False)),
                ('nama_mitra', models.CharField(max_length=100)),
                ('alamat_mitra', models.TextField(blank=True, null=True)),
                ('nohp_mitra', models.PositiveBigIntegerField()),
                ('tanggalawal_mitra', models.DateField()),
                ('durasi_kontrak', models.PositiveIntegerField()),
                ('luas_lahan', models.PositiveIntegerField(null=True)),
                ('status_mitra', models.BooleanField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='panenlokal',
            fields=[
                ('idpanen_lokal', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_panen', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='pasar',
            fields=[
                ('id_pasar', models.AutoField(primary_key=True, serialize=False)),
                ('nama_pasar', models.CharField(max_length=100)),
                ('alamat_pasar', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='produk',
            fields=[
                ('id_produk', models.AutoField(primary_key=True, serialize=False)),
                ('nama_produk', models.CharField(max_length=100)),
                ('satuan_produk', models.CharField(max_length=100)),
                ('harga_produk', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='produksi',
            fields=[
                ('id_produksi', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('status_produk', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='penjualan',
            fields=[
                ('id_penjualan', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('id_pasar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.pasar')),
            ],
        ),
        migrations.CreateModel(
            name='panenmitra',
            fields=[
                ('idpanen_mitra', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_panen', models.DateField()),
                ('id_mitra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.mitra')),
            ],
        ),
        migrations.CreateModel(
            name='komoditas',
            fields=[
                ('id_komoditas', models.AutoField(primary_key=True, serialize=False)),
                ('nama_komoditas', models.CharField(max_length=100)),
                ('harga_beli', models.IntegerField()),
                ('harga_jual', models.IntegerField()),
                ('id_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.grade')),
            ],
        ),
        migrations.CreateModel(
            name='detailproduksi',
            fields=[
                ('iddetail_produksi', models.AutoField(primary_key=True, serialize=False)),
                ('kuantitas_produk', models.PositiveIntegerField()),
                ('id_produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.produk')),
                ('id_produksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.produksi')),
            ],
        ),
        migrations.CreateModel(
            name='detailpenjualan',
            fields=[
                ('iddetail_penjualan', models.AutoField(primary_key=True, serialize=False)),
                ('kuantitas_komoditas', models.PositiveIntegerField(null=True)),
                ('kuantitas_produk', models.PositiveIntegerField(null=True)),
                ('id_komoditas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guava.komoditas')),
                ('id_penjualan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.penjualan')),
                ('id_produk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guava.produk')),
            ],
        ),
        migrations.CreateModel(
            name='detailpanenmitra',
            fields=[
                ('iddetailpanen_mitra', models.AutoField(primary_key=True, serialize=False)),
                ('batch', models.PositiveIntegerField()),
                ('tanggal_kadaluwarsa', models.DateField()),
                ('kuantitas', models.PositiveIntegerField()),
                ('id_komoditas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.komoditas')),
                ('idpanen_mitra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.panenmitra')),
            ],
        ),
        migrations.CreateModel(
            name='detailpanenlokal',
            fields=[
                ('iddetailpanen_lokal', models.AutoField(primary_key=True, serialize=False)),
                ('batch', models.PositiveIntegerField()),
                ('tanggal_kadaluwarsa', models.DateField()),
                ('kuantitas', models.PositiveIntegerField(null=True)),
                ('id_komoditas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.komoditas')),
                ('idpanen_lokal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.panenlokal')),
            ],
        ),
        migrations.CreateModel(
            name='biaya',
            fields=[
                ('idbiaya', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('nama_biaya', models.CharField(max_length=100)),
                ('nominal_biaya', models.PositiveIntegerField()),
                ('idjenisbiaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.jenisbiaya')),
            ],
        ),
    ]
